sudo: required
dist: trusty
language: generic
services:
  - docker
cache:
  directories:
  - .cache
branches:
  only:
    - /^20.*$/
    - master

# Travis CI build matrix.  Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
  - os: linux
    env:
     - COBBLER_ARCH=arm64
     - COBBLER_GIT_ENDPOINT=https://github.com/Microsoft/vscode
#  - os: linux
#    env:
#     - arch="armhf"
#     - COBBLER_GIT_ENDPOINT=https://github.com/Microsoft/vscode
    
notifications:
  email: false
  
before_install:
  - gem install package_cloud;
  - sudo apt-get install -y tree;
  - export TRAVIS_OUTPUT_DIRECTORY=$(pwd)/output; # Travis does not specify an output artifact directory, so we'll create our own.

script:
  - mkdir $TRAVIS_OUTPUT_DIRECTORY;
  - sudo bash -c '. ./dock.sh build $TRAVIS_OUTPUT_DIRECTORY';
  
after_success:
  - package_cloud push headmelted/codebuilds/ubuntu/xenial $TRAVIS_OUTPUT_DIRECTORY/*.deb
  - package_cloud push headmelted/codebuilds/fedora/24 $TRAVIS_OUTPUT_DIRECTORY/*.rpm

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - $(pwd)/output/*.*
  skip_cleanup: true
  on:
    repo: headmelted/codebuilds
    tags: true
 
