resources:
- repo: https://github.com/headmelted/codebuilds.git

trigger:
- master

jobs:
- job: linux_arm32
  displayName: 'Linux ARM (32-bit)'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: cobble@0
    displayName: Cobble
    action: 'Run Cobbler to build the packages for a given architecture'
    imageName: 'headmelted/cobbler'
    volumes: |
      $(Build.SourcesDirectory)/cobbler:/cobbler
    envVars: |
      ARCH=armhf
    workDir: '/kitchen'
    containerCommand: 'cook.sh'

