resources:
- repo: self

trigger:
- master

pool:
- vmImage: 'Ubuntu 16.04'

jobs:
- job: linux_armhf
  displayName: 'Linux ARM 32-bit, hardware floating-point'
  steps:
  - template: devops-cobbler.yml
- job: linux_arm64
  displayName: 'Linux ARM 64-bit'
  steps:
  - template: devops-cobbler.yml
  
