resources:
- repo: self

trigger:
- master

jobs:
- job: linux_arm64
  displayName: 'Linux ARM 64-bit'
  steps:
  - template: devops-cobbler.yml
    parameters:
      envVars: |
       COBBLER_GIT_ENDPOINT=https://github.com/Microsoft/vscode
    
#- job: linux_arm32hf
#  displayName: 'Linux ARM 32-bit, hardware floating-point'
#  steps:
#  - template: devops-cobbler.yml
  
