resources:
- repo: self

trigger:
- master

parameters:
  build: |
      echo "Running npm install for [$npm_config_target_arch]";
      npm install --unsafe-perm;
      echo "Compiling VS Code for [$npm_config_target_arch]";
      yarn run gulp vscode-linux-$npm_config_target_arch-min;

jobs:
- job: linux_arm64
  displayName: 'Linux ARM 64-bit'
  steps:
  - template: devops-cobbler.yml
    parameters:
      build: ${{parameters.build}}
      
#- job: linux_arm32hf
#  displayName: 'Linux ARM 32-bit, hardware floating-point'
#  steps:
#  - template: devops-cobbler.yml
