resources:
- repo: self

trigger:
- master

jobs:
- job: linux_xenial_arm32
  displayName: 'Linux (Xenial; arm32)'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: vsts-cobble-docker.yml
        
